[package]
name = "pulsevm_error"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
thiserror = "2"
wasmer = { version = "6.1.0" }
cxx = "1.0.194"
jsonrpsee = { version = "0.24.9", features = ["server", "macros"] }