name: Build release artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-amd64:
    runs-on: ubuntu-24.04

    steps:
      - name: Configure LLVM APT repository
        run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - && sudo echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-21 main" | sudo tee /etc/apt/sources.list.d/llvm.list

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-13 g++-13 cmake libgmp-dev zlib1g-dev pkg-config libcurl4-openssl-dev libboost-all-dev llvm-21-dev libpolly-21-dev

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Protobuf (protoc)
        uses: arduino/setup-protoc@v2
        with:
          version: '27.1' # choose your required version

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release artifact
        run: CXX=/usr/bin/g++-13 CC=/usr/bin/gcc-13 LLVM_SYS_211_PREFIX=/usr/lib/llvm-21 cargo build --release
